### PR TITLE
Rewl

### PR DESCRIPTION
**Pull request by mswwilson**
There's still some changes and additions to be made, but will do those in separate commits/PR when necessary. 

REWL2D.jl works but will have limited use because it is very slow to converge for practical system sizes.

### CODE REVIEW

**Comment by kbarros** [comment]
Thanks for the PR Matt. Given her expertise, I wonder if @yingwaili should do the first review?

**Comment by kbarros** [comment]
I attempted to rebase onto main branch, but very likely there are errors that need to be manually fixed. Matt, let's sit down together and attempt to update.

**Comment by mswwilson** [comment]
Sounds good - let me know whenever you want to go through it

**Comment by kbarros** [comment]
Matt, given your refactors in progress, should we go ahead and close this PR? Before I do so, please make sure you have everything backed up.

**Comment by mswwilson** [comment]
Hey Kipton, I'm fine with closing the PR, thanks.

**Pull request closed without merging**
